### ISSUE TITLE
ESDoc.generate

### ISSUE THREAD

**Issue by exos** [nanopx/gulp-esdoc#18]
gulpfile:
```
gulp.task('docs', ['clean-docs'], () => {
    let config = require('./.esdoc.json');

    return gulp.src([
        'src',
    ])
        .pipe(esdoc(config));
});

```

```
/home/exos/alpha/expressolite-project/expressolite/node_modules/gulp-esdoc/index.js:42
    ESDoc.generate(config, publisher);
          ^

TypeError: ESDoc.generate is not a function
    at DestroyableTransform.flush [as _flush] (/home/exos/alpha/expressolite-project/expressolite/node_modules/gulp-esdoc/index.js:42:11)
    at DestroyableTransform.<anonymous> (/home/exos/alpha/expressolite-project/expressolite/node_modules/readable-stream/lib/_stream_transform.js:115:49)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:188:7)
    at prefinish (/home/exos/alpha/expressolite-project/expressolite/node_modules/readable-stream/lib/_stream_writable.js:494:12)
    at finishMaybe (/home/exos/alpha/expressolite-project/expressolite/node_modules/readable-stream/lib/_stream_writable.js:502:7)
    at endWritable (/home/exos/alpha/expressolite-project/expressolite/node_modules/readable-stream/lib/_stream_writable.js:514:3)
    at DestroyableTransform.Writable.end (/home/exos/alpha/expressolite-project/expressolite/node_modules/readable-stream/lib/_stream_writable.js:484:41)
    at DestroyableTransform.onend (/home/exos/alpha/expressolite-project/expressolite/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:523:10)
```

**Comment by ericberens** [comment]
Resolved by #16
