### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by NullDivision** [nanopx/gulp-esdoc#9]
I'm getting a RangeError for whatever reason using `gulp-esdoc`.

```
/home/nulldivision/MyProject/node_modules/esdoc/out/src/Publisher/Builder/DocResolver.js:95
            throw _iteratorError;
            ^

RangeError: Maximum call stack size exceeded
    at module.exports (/home/nulldivision/MyProject/node_modules/babel-polyfill/node_modules/core-js/modules/_an-object.js:2:26)
    at RegExp.toString (/home/nulldivision/MyProject/node_modules/babel-polyfill/node_modules/core-js/modules/es6.regexp.to-string.js:16:13)
    at String (native)
    at RegExp.<anonymous> (/home/nulldivision/MyProject/node_modules/esdoc/node_modules/core-js/modules/$.replacer.js:7:12)
    at RegExp.toString (/home/nulldivision/MyProject/node_modules/babel-polyfill/node_modules/core-js/modules/es6.regexp.to-string.js:18:23)
    at String (native)
    at RegExp.<anonymous> (/home/nulldivision/MyProject/node_modules/esdoc/node_modules/core-js/modules/$.replacer.js:7:12)
    at RegExp.toString (/home/nulldivision/MyProject/node_modules/babel-polyfill/node_modules/core-js/modules/es6.regexp.to-string.js:18:23)
    at String (native)
    at RegExp.<anonymous> (/home/nulldivision/MyProject/node_modules/esdoc/node_modules/core-js/modules/$.replacer.js:7:12)
```

Config:

```
{
  "source": "./",
  "destination": "esdoc/dist/api-doc/src",
  "includes": [
    "\\.js$"
  ],
  "excludes": [
    "gulpfile.babel.js",
    "coverage",
    "dist",
    "node_modules",
    "test"
  ],
  "plugins": [
    {
      "name": "esdoc-importpath-plugin",
      "option": {
        "replaces": [
          {
            "from": "\\.js$",
            "to": ""
          }
        ]
      }
    }
  ],
  "styles": [
    "./esdoc/esdoc.css"
  ],
  "title": "MyProject"
}
```

This doesn't happen with CLI `eslint`.

**Comment by NullDivision** [comment]
I think this is an incompatibility with a common  dep with eslint. (Possibly espree I would guess). Updating to gulp-eslint v2.0.0 fixed it.

**Comment by NullDivision** [comment]
Or apparently not. Reinstalled node modules and the error is back.

**Comment by ghost** [comment]
Try this: `$ gulp esDoc --max_old_space_size=8192`
